print("Data Science Tools and Ecosystem")
print('Author')
print('name:xcea')
print('In this notebook, Data Science Tools and Ecosystem are summarized.')
print('Objectives:I learned some basic theory of data science.unordered list:List popular languages for Data Science, Create a code cell to convert minutes to hoursCreate a code cell to multiply,and add numbers')
print("Some of the popular languages that Data Scientists use are:")
print("ordered list: Python,R,SQL,Scala,Java,C++,Julia")
print('Some of the commonly used libraries used by Data Scientists include:')
print("ordered list:Pandas,NumPy,SciPy,Matplotlib")
print("Data Science Tools:PyCharm,Anaconda,Jupyter")
print("Below are a few examples of evaluating arithmetic expressions in Python")
print('This a simple arithmetic expression to mutiply then add integers  '+str((3*4)+5))
print('This will convert 200 minutes to hours by diving by 60  '+str(200/60))
